DROP TABLE EMPLEADO;
DROP TABLE DEPARTAMENTO;

create table DEPARTAMENTO(
    CODIGO INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL
);

CREATE TABLE EMPLEADO(
    RUT INTEGER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELLIDO VARCHAR2(30) NOT NULL,
    SUELDO INTEGER NOT NULL,
    FECHA_CONTRATO DATE NOT NULL,
    DEPARTAMENTO_CODIGO INTEGER NOT NULL
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT DEPARTAMENTO_FK
FOREIGN KEY (DEPARTAMENTO_CODIGO) 
REFERENCES DEPARTAMENTO(CODIGO);

/*COMANDOS DML*/
/*INSERT = INSERTAR DATA EN UNA TABLA*/

INSERT INTO DEPARTAMENTO VALUES(10,'RRHH');
INSERT INTO DEPARTAMENTO VALUES(20,'TI');
INSERT INTO DEPARTAMENTO VALUES(30,'FINANZAS');
INSERT INTO DEPARTAMENTO VALUES(40,'PREVENCION DE RIESGOS');
INSERT INTO DEPARTAMENTO VALUES(50,'LOGISTICA');
INSERT INTO "EJEMPLODML"."DEPARTAMENTO" (CODIGO, NOMBRE) VALUES ('70', 'MARKETING');

INSERT INTO EMPLEADO VALUES(1111,'PEDRO','LARA',350000,TO_DATE('01/01/2022'),50);
INSERT INTO EMPLEADO VALUES(2222,'JAVIERA','PARRA',300000,TO_DATE('10/09/2022'),20);
INSERT INTO EMPLEADO VALUES(3333,'ANA','MONSLAVE',450000,TO_DATE('05/02/2023'),30);
INSERT INTO EMPLEADO VALUES(4444,'CAMILO','SOTO',650000,TO_DATE('12/11/2023'),30);
INSERT INTO EMPLEADO VALUES(5555,'VALENTINA','PEÑA',750000,SYSDATE,10);



/*CONSULTA BASE DE DATOS*/
SELECT * FROM EMPLEADO;
SELECT * FROM EMPLEADO WHERE RUT='1111';
SELECT * FROM EMPLEADO WHERE DEPARTAMENTO_CODIGO = 30;
SELECT * FROM EMPLEADO WHERE SUELDO<450000;

/* || PARA CONCATENAR
SE PUDEN HACER CALCULOS MATEMATIOCS SUELDO*1.2
SE PUEDE RENOMBRAR VARIABLES CON "" 
ORDENAR CON ORDER, POR DEFECTO ES MENOR A MAYOR, Y CON DESC ES MAYOR A MENOR*/
SELECT  INITCAP(nombre||' '||apellido) "NOMBRE COMPLETO",
        sueldo"SUELDO ANTIGUO",
        sueldo*1.2 "NUEVO SUELDO"
FROM EMPLEADO
ORDER BY sueldo*1.2 DESC; 

/*TSL
COMMIT, GUARDA LOS DATOS Y TABLAS
SAVEPOINT, PUNTO DE GUARDADO PARA VOLVER POR SI LA EMBARRO
ROLLBACK, REGRESAR A EL PUNTO DE GUARDADO*/
COMMIT;
SAVEPOINT A1; 
ROLLBACK TO A1;
/*DELETE = BORRAR
UPDATE = ACTUALIZAR / MODIFICAR INFORMACION*/
DELETE FROM EMPLEADO WHERE RUT = 5555;
UPDATE EMPLEADO SET sueldo= SUELDO-200000 WHERE RUT = 5555;

